name: pipeline iac

run-name: ${{ github.actor }} iniciou o pipeline

on:
  push:
    branches:
      - main


jobs:
    terraform:
        name: Terraform Validation & Security
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.0.0

            - name: Terraform Format
              run: terraform fmt -check

            - name: Terraform Init
              run: terraform init
            
            - name: Terraform Validate
              run: terraform validate
            
            - name: Run tfsec
              uses: aquasecurity/tfsec-action@v1.0.0

            - name: Configurar chave SSH
              run: |
                mkdir -p ~/.ssh
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh-keyscan github.com >> ~/.ssh/known_hosts

            - name: Terraform Plan
              run: terraform plan -out=tfplan
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    tests:
        name: Terraform Tests
        runs-on: ubuntu-latest
        needs: terraform

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v2
              with:
                terraform_version: 1.0.0

            - name: Terraform Init
              run: terraform init

            - name: Run Terraform Tests
              run: terraform test